name: Deploy
on:
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run type-check
      - run: bun run lint
      - run: bun run formatjs-extract && bun run formatjs-verify
      - run: bun test

  deploy-dokku:
    name: Deploy to Dokku
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: dokku/github-action@v1.9.0
        with:
          branch: "main"
          git_push_flags: ${{ github.event.forced && '--force' || '' }}
          git_remote_url: ${{ vars.GIT_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
